### ISSUE TITLE
[Bug] Add widget background fail on iPad.

### ISSUE THREAD

**Issue by Bill-Haku** [pizza-studio/HSRPizzaHelper#132]
**Describe the bug**
Directly go back to settings view on iPad. 

See this [video](https://discord.com/channels/1013415539298816060/1124974054647021598/1140630443574710395) for details

**Comment by CanglongCl** [comment]
ack

**Comment by ShikiSuen** [comment]
I'm closing this ticket now since the customized widget background feature is missing in the United Pizza Helper v5.0.0. This feature will be brought back in the future if convenient.

Memo: When rewriting this feature, use Apple built-in API in lieu of 3rd-party SPM dependency for handling image resizing and reencoding process.
