### ISSUE TITLE
[Bug] Character Avatar Display

### ISSUE THREAD

**Issue by Lucas04-nhr** [pizza-studio/HSRPizzaHelper#196]
**Describe the bug**
The display of the avatar of the new character Firefly in the warp analysis seems abnormal("NULL-CHAR(1310)"), but that in the Details of "My character" is normal.

**To Reproduce**
1. Go to 'Tools'
2. Click on 'Warp Analysis'
3. Get the warp record

**Expected behavior**
Firefly's real name and avatar.

**Screenshots**
<img width="1373" alt="image" src="https://github.com/pizza-studio/HSRPizzaHelper/assets/117806313/c271ec02-f6ba-4d08-8864-1e3ee184fc7d">

**System (please complete the following information):**
 - Device: iPad Air (5th Gen)
 - OS: iPadOS 17.5.1
 - Version 1.3.8
 - Build 707

**Additional context**
None.

**Comment by ShikiSuen** [comment]
Could you please share a copy of your gacha log (SRGF) for us to debug this issue?

**Comment by ShikiSuen** [comment]
BTW the char 1310 is Hotaru (流萤). Its avatar was censored by MiHoYo in HSR v2.0 - v2.2 for confidential purposes. The image asset has been fixed in PizzaHelper4HSR v1.3.9-RC.3-727.

For now you may try putting Hotaru into your ShowCase and try loading the showcase in this app. This will trigger the update of EnkaDB to make sure character names are all loadable. We'll fix the character name API in this view in the next app update.

**Comment by Lucas04-nhr** [comment]
> BTW the char 1310 is Hotaru (流萤). Its avatar was censored by MiHoYo in HSR v2.0 - v2.2 for confidential purposes. The image asset has been fixed in PizzaHelper4HSR v1.3.9-RC.3-727.
> 
> For now you may try putting Hotaru into your ShowCase and try loading the showcase in this app. This will trigger the update of EnkaDB to make sure character names are all loadable. We'll fix the character name API in this view in the next app update.

It seems work through this workaround, thanks!
